export const ADD_OPERATION= 'APP/CALCULATOR/ADD_OPPERATION'; 
export const CALCULATE = 'APP/CALCULATOR/CALCULATE';
export const RENEW = 'APP/CALCULATOR/RENEW';
export const ADD_RESULT = 'APP/CALCULATOR/ADD_RESULT';